### ISSUE TITLE
Push from Osehra

### ISSUE THREAD

**Issue by MelindaPGentry** [department-of-veterans-affairs/FOIA-VistA-DBA#2]
@froi do you have an estimated time when the download you have from OSHERA will be uploaded to the https://github.com/department-of-veterans-affairs/FOIA-VistA-DBA
repository?

@amandawalling  @johnbeister

**Comment by MelindaPGentry** [comment]
@froi any update?

**Comment by froi** [comment]
Sorry for the radio silence. I was out of office.

The linked pull requests uploads all files found in the OSEHRA site before it was shutdown.

Because of the size of this repository, about 68GB I believe, it took some time to upload all of the content. I recommend not making repositories of this size in the future. 

@MelindaPGentry I'd love to have a consultation session about this. 

@selkins13, @allthedoll have we had a similar session?
